# Generated by Django 5.2.6 on 2025-09-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, help_text='닉네임을 설정하지 않으면 사용자명이 표시됩니다.', max_length=30, null=True),
        ),
    ]
