# Generated by Django 5.2.6 on 2025-09-29 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_profile_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='프로필 이미지를 업로드하세요.', null=True, upload_to='profile_images/'),
        ),
    ]
