# Generated by Django 5.2.6 on 2025-09-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_profile_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('code', models.CharField(max_length=4, verbose_name='인증코드')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='인증일시')),
                ('is_verified', models.BooleanField(default=False, verbose_name='인증완료')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='시도횟수')),
            ],
            options={
                'verbose_name': '이메일 인증',
                'verbose_name_plural': '이메일 인증',
                'ordering': ['-created_at'],
            },
        ),
    ]
