# Generated by Django 5.2.6 on 2025-10-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_emailverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='KakaoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kakao_id', models.BigIntegerField(unique=True, verbose_name='카카오 ID')),
                ('nickname', models.CharField(blank=True, max_length=100, null=True, verbose_name='닉네임')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='이메일')),
                ('profile_image', models.URLField(blank=True, null=True, verbose_name='프로필 이미지')),
                ('thumbnail_image', models.URLField(blank=True, null=True, verbose_name='썸네일 이미지')),
                ('access_token', models.TextField(verbose_name='액세스 토큰')),
                ('refresh_token', models.TextField(blank=True, null=True, verbose_name='리프레시 토큰')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='토큰 만료 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='가입일')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='최근 로그인')),
            ],
            options={
                'verbose_name': '카카오 사용자',
                'verbose_name_plural': '카카오 사용자들',
                'db_table': 'kakao_users',
            },
        ),
    ]
