# Generated by Django 5.2.6 on 2025-10-23 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_kakaouser'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rank',
            field=models.CharField(choices=[('regular', '일반회원'), ('member', '정회원'), ('tech_chang', '테크창')], default='regular', max_length=20, verbose_name='회원 등급'),
        ),
    ]
