# Generated by Django 5.2.6 on 2025-10-28 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_profile_rank'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emoticon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이모티콘 이름')),
                ('image', models.ImageField(upload_to='emoticons/', verbose_name='이모티콘 이미지')),
                ('price', models.IntegerField(verbose_name='가격 (포인트)')),
                ('is_available', models.BooleanField(default=True, verbose_name='판매 중')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '이모티콘',
                'verbose_name_plural': '이모티콘 목록',
                'ordering': ['price', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='points',
            field=models.IntegerField(default=0, verbose_name='포인트'),
        ),
        migrations.AddField(
            model_name='profile',
            name='selected_emoticon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_by', to='common.emoticon', verbose_name='선택한 이모티콘'),
        ),
        migrations.CreateModel(
            name='PointHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='포인트 변동량')),
                ('reason', models.CharField(choices=[('checkin', '출석 체크'), ('purchase', '이모티콘 구매'), ('admin', '관리자 지급'), ('game', '게임 보상')], max_length=20, verbose_name='사유')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='상세 설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_history', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '포인트 히스토리',
                'verbose_name_plural': '포인트 히스토리 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(auto_now_add=True, verbose_name='출석일')),
                ('points_earned', models.IntegerField(default=5, verbose_name='획득 포인트')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '출석 체크',
                'verbose_name_plural': '출석 체크 목록',
                'ordering': ['-check_in_date'],
                'unique_together': {('user', 'check_in_date')},
            },
        ),
        migrations.CreateModel(
            name='UserEmoticon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name='구매일')),
                ('emoticon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.emoticon', verbose_name='이모티콘')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_emoticons', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '구매한 이모티콘',
                'verbose_name_plural': '구매한 이모티콘 목록',
                'ordering': ['-purchased_at'],
                'unique_together': {('user', 'emoticon')},
            },
        ),
    ]
