# Generated by Django 5.2.6 on 2025-10-30 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_emoticon_profile_points_profile_selected_emoticon_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='IP 주소')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='차단 사유')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='차단일시')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('blocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_ips', to=settings.AUTH_USER_MODEL, verbose_name='차단한 관리자')),
            ],
            options={
                'verbose_name': '차단된 IP',
                'verbose_name_plural': '차단된 IP 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
