# Generated by Django 5.2.6 on 2025-12-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_blockedip'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text='이메일 인증을 완료한 사용자인지 여부', verbose_name='이메일 인증 여부'),
        ),
    ]
