# Generated by Django 5.2.6 on 2025-12-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_profile_is_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='code',
            field=models.CharField(max_length=6, verbose_name='인증코드'),
        ),
    ]
