# Generated by Django 5.2.6 on 2026-02-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_alter_emailverification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='code',
            field=models.CharField(max_length=10, verbose_name='인증코드'),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='생성일시'),
        ),
        migrations.AddIndex(
            model_name='emailverification',
            index=models.Index(fields=['email', 'created_at'], name='common_emai_email_d4e356_idx'),
        ),
    ]
