# Generated by Django 5.2.6 on 2026-06-13 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_set_site_domain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='지문(중복 방지)')),
                ('title', models.CharField(max_length=300, verbose_name='문제 제목')),
                ('cause', models.TextField(blank=True, verbose_name='추정 원인')),
                ('action', models.TextField(blank=True, verbose_name='권장 조치')),
                ('severity', models.CharField(blank=True, max_length=20, verbose_name='심각도')),
                ('overview', models.TextField(blank=True, verbose_name='총평')),
                ('status', models.CharField(choices=[('pending', '대기'), ('approved', '승인'), ('rejected', '거부'), ('dispatched', '작업 전달됨')], db_index=True, default='pending', max_length=20, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='최초 감지일시')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='결정일시')),
                ('pr_url', models.URLField(blank=True, verbose_name='생성된 PR URL')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='비고')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_findings', to=settings.AUTH_USER_MODEL, verbose_name='결정한 관리자')),
            ],
            options={
                'verbose_name': 'AI 로그 지적사항',
                'verbose_name_plural': 'AI 로그 지적사항 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
