# Generated by Django 5.2.6 on 2026-10-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_logfinding'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='terms_agreed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='약관 동의 일시'),
        ),
        migrations.AddField(
            model_name='profile',
            name='terms_version',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='동의한 약관 버전'),
        ),
    ]
