# Generated by Django 5.2.6 on 2025-09-25 07:15

from django.db import migrations

def create_categories(apps, schema_editor):
    Category = apps.get_model('community', 'Category')
    Question = apps.get_model('community', 'Question')
    
    # 기본 카테고리 생성
    categories = [
        {'name': '질문답변', 'description': '일반적인 질문과 답변을 위한 게시판'},
        {'name': '자유게시판', 'description': '자유로운 주제의 토론을 위한 게시판'},
        {'name': '강좌', 'description': '학습 자료와 강의를 위한 게시판'},
        {'name': '공지사항', 'description': '중요한 공지사항을 위한 게시판'},
    ]

    default_category = None
    for category_data in categories:
        category, created = Category.objects.get_or_create(
            name=category_data['name'],
            defaults={'description': category_data['description']}
        )
        # 첫 번째 카테고리를 기본 카테고리로 설정
        if category_data['name'] == '질문답변':
            default_category = category

    # 카테고리가 없는 기존 질문들에 기본 카테고리 할당
    if default_category:
        Question.objects.filter(category__isnull=True).update(category=default_category)

def reverse_categories(apps, schema_editor):
    Category = apps.get_model('community', 'Category')
    Category.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_category_question_view_count_question_category_and_more'),
    ]

    operations = [
        migrations.RunPython(create_categories, reverse_categories),
    ]
