# Generated by Django 5.2.6 on 2025-09-29 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0010_question_image'),
    ]

    operations = [
    ]
