# Generated by Django 5.2.6 on 2025-09-30 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0012_answer_deleted_date_answer_is_deleted_and_more'),
    ]

    operations = [
    ]
