# Generated by Django 5.2.6 on 2025-10-23 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0016_wordchaingame_current_turn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='회원 전용 글 (로그인 필요)'),
        ),
    ]
