# Generated by Django 5.2.6 on 2025-10-27 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0017_question_is_locked'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=200, verbose_name='내용')),
                ('color', models.CharField(choices=[('#fff475', '노란색'), ('#ff7eb9', '핑크색'), ('#7afcff', '하늘색'), ('#c7f0bd', '연두색'), ('#ffc891', '주황색'), ('#d9b3ff', '보라색')], default='#fff475', max_length=7, verbose_name='색상')),
                ('position_x', models.IntegerField(default=0, verbose_name='X 위치')),
                ('position_y', models.IntegerField(default=0, verbose_name='Y 위치')),
                ('rotation', models.FloatField(default=0, verbose_name='회전 각도')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guestbook_entries', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '방명록',
                'verbose_name_plural': '방명록 목록',
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='NumberBaseballGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_number', models.CharField(max_length=4, verbose_name='정답 숫자')),
                ('attempts', models.IntegerField(default=0, verbose_name='시도 횟수')),
                ('max_attempts', models.IntegerField(default=10, verbose_name='최대 시도 횟수')),
                ('status', models.CharField(choices=[('playing', '진행중'), ('won', '성공'), ('giveup', '포기')], default='playing', max_length=10, verbose_name='상태')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='종료일')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baseball_games', to=settings.AUTH_USER_MODEL, verbose_name='플레이어')),
            ],
            options={
                'verbose_name': '숫자야구 게임',
                'verbose_name_plural': '숫자야구 게임 목록',
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='NumberBaseballAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guess_number', models.CharField(max_length=4, verbose_name='추측 숫자')),
                ('strikes', models.IntegerField(verbose_name='스트라이크')),
                ('balls', models.IntegerField(verbose_name='볼')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='시도 시간')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_records', to='community.numberbaseballgame', verbose_name='게임')),
            ],
            options={
                'verbose_name': '숫자야구 시도',
                'verbose_name_plural': '숫자야구 시도 기록',
                'ordering': ['create_date'],
            },
        ),
        migrations.CreateModel(
            name='TicTacToeGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='게임 제목')),
                ('current_turn', models.CharField(choices=[('X', 'X'), ('O', 'O')], default='X', max_length=1, verbose_name='현재 턴')),
                ('board_state', models.JSONField(default=list, verbose_name='보드 상태')),
                ('status', models.CharField(choices=[('waiting', '대기중'), ('playing', '진행중'), ('finished', '종료')], default='waiting', max_length=10, verbose_name='상태')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='시작일')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='종료일')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tictactoe_games', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('player_o', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tictactoe_o', to=settings.AUTH_USER_MODEL, verbose_name='플레이어 O')),
                ('player_x', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tictactoe_x', to=settings.AUTH_USER_MODEL, verbose_name='플레이어 X')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_tictactoe_games', to=settings.AUTH_USER_MODEL, verbose_name='승자')),
            ],
            options={
                'verbose_name': '틱택토 게임',
                'verbose_name_plural': '틱택토 게임 목록',
                'ordering': ['-create_date'],
            },
        ),
    ]
