# Generated by Django 5.2.6 on 2025-10-28 04:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0019_game2048'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='game2048',
            name='best_score',
            field=models.IntegerField(db_index=True, default=0, verbose_name='최고 점수'),
        ),
        migrations.AlterField(
            model_name='game2048',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='game2048',
            name='status',
            field=models.CharField(choices=[('playing', '진행중'), ('won', '승리'), ('lost', '패배')], db_index=True, default='playing', max_length=10, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='guestbook',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='작성일'),
        ),
        migrations.AlterField(
            model_name='numberbaseballgame',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='numberbaseballgame',
            name='status',
            field=models.CharField(choices=[('playing', '진행중'), ('won', '성공'), ('giveup', '포기')], db_index=True, default='playing', max_length=10, verbose_name='상태'),
        ),
        migrations.AddIndex(
            model_name='game2048',
            index=models.Index(fields=['player', 'status'], name='g2048_player_status_idx'),
        ),
        migrations.AddIndex(
            model_name='game2048',
            index=models.Index(fields=['player', '-best_score'], name='g2048_player_best_idx'),
        ),
        migrations.AddIndex(
            model_name='game2048',
            index=models.Index(fields=['player', '-create_date'], name='g2048_player_date_idx'),
        ),
        migrations.AddIndex(
            model_name='guestbook',
            index=models.Index(fields=['-create_date'], name='gb_create_date_idx'),
        ),
        migrations.AddIndex(
            model_name='numberbaseballgame',
            index=models.Index(fields=['player', 'status'], name='bb_player_status_idx'),
        ),
        migrations.AddIndex(
            model_name='numberbaseballgame',
            index=models.Index(fields=['player', '-create_date'], name='bb_player_date_idx'),
        ),
    ]
