# Generated by Django 5.2.6 on 2025-10-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0022_alter_minesweepergame_board_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['create_date']},
        ),
        migrations.AddField(
            model_name='game2048',
            name='difficulty',
            field=models.CharField(choices=[('normal', '일반 (시간 무제한)'), ('hard', '하드 (비활동 시간 제한)')], default='normal', max_length=10, verbose_name='난이도'),
        ),
        migrations.AddField(
            model_name='game2048',
            name='inactivity_limit',
            field=models.IntegerField(default=0, verbose_name='비활동 제한 (초)'),
        ),
        migrations.AddField(
            model_name='game2048',
            name='last_activity_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='마지막 활동 시간'),
        ),
        migrations.AddField(
            model_name='numberbaseballgame',
            name='consecutive_misses',
            field=models.IntegerField(default=0, verbose_name='연속 실패 횟수'),
        ),
        migrations.AddField(
            model_name='numberbaseballgame',
            name='difficulty',
            field=models.CharField(choices=[('normal', '일반 (10회 시도, 시간 무제한)'), ('hard', '하드 (7회 시도, 5분 제한)')], default='normal', max_length=10, verbose_name='난이도'),
        ),
        migrations.AddField(
            model_name='numberbaseballgame',
            name='inactivity_limit',
            field=models.IntegerField(default=0, verbose_name='비활동 제한 (초)'),
        ),
        migrations.AddField(
            model_name='numberbaseballgame',
            name='last_activity_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='마지막 활동 시간'),
        ),
        migrations.AddField(
            model_name='numberbaseballgame',
            name='time_elapsed',
            field=models.IntegerField(default=0, verbose_name='경과 시간 (초)'),
        ),
        migrations.AddField(
            model_name='numberbaseballgame',
            name='time_limit',
            field=models.IntegerField(default=0, verbose_name='시간 제한 (초)'),
        ),
        migrations.AlterField(
            model_name='game2048',
            name='status',
            field=models.CharField(choices=[('playing', '진행중'), ('won', '승리'), ('lost', '패배'), ('timeout', '시간초과')], db_index=True, default='playing', max_length=10, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='numberbaseballgame',
            name='status',
            field=models.CharField(choices=[('playing', '진행중'), ('won', '성공'), ('giveup', '포기'), ('timeout', '시간초과')], db_index=True, default='playing', max_length=10, verbose_name='상태'),
        ),
    ]
