# Generated by Django 5.2.6 on 2025-10-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0023_alter_comment_options_game2048_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestbook',
            name='font_family',
            field=models.CharField(choices=[('Gungsuh', '궁서체'), ('Nanum Gothic', '나눔고딕'), ('Nanum Myeongjo', '나눔명조'), ('Nanum Pen Script', '나눔손글씨'), ('Jua', '주아체'), ('Do Hyeon', '도현체'), ('Black Han Sans', '검은고딕')], default='Gungsuh', max_length=50, verbose_name='글꼴'),
        ),
    ]
