# Generated by Django 5.2.6 on 2025-12-17 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0024_guestbook_font_family'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100, verbose_name='직업/역할')),
                ('bio', models.TextField(blank=True, default='', max_length=500, verbose_name='자기소개')),
                ('location', models.CharField(blank=True, default='', max_length=100, verbose_name='위치')),
                ('email', models.EmailField(blank=True, default='', max_length=100, verbose_name='이메일')),
                ('github_url', models.URLField(blank=True, default='', verbose_name='GitHub URL')),
                ('linkedin_url', models.URLField(blank=True, default='', verbose_name='LinkedIn URL')),
                ('website_url', models.URLField(blank=True, default='', verbose_name='개인 웹사이트')),
                ('skills', models.JSONField(blank=True, default=list, verbose_name='기술 스택')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='portfolio/profiles/', verbose_name='프로필 이미지')),
                ('is_public', models.BooleanField(default=True, verbose_name='공개 여부')),
                ('theme', models.CharField(choices=[('light', '라이트 모드'), ('dark', '다크 모드')], default='light', max_length=10, verbose_name='테마')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '포트폴리오',
                'verbose_name_plural': '포트폴리오 목록',
                'db_table': 'pybo_portfolio',
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='프로젝트 제목')),
                ('description', models.TextField(verbose_name='프로젝트 설명')),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/projects/', verbose_name='프로젝트 이미지')),
                ('tech_stack', models.JSONField(blank=True, default=list, verbose_name='기술 스택')),
                ('project_url', models.URLField(blank=True, default='', verbose_name='프로젝트 URL')),
                ('github_url', models.URLField(blank=True, default='', verbose_name='GitHub URL')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='시작일')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='종료일')),
                ('order', models.IntegerField(default=0, verbose_name='순서')),
                ('is_featured', models.BooleanField(default=False, verbose_name='추천 프로젝트')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='community.portfolio', verbose_name='포트폴리오')),
            ],
            options={
                'verbose_name': '프로젝트',
                'verbose_name_plural': '프로젝트 목록',
                'db_table': 'pybo_project',
                'ordering': ['order', '-create_date'],
            },
        ),
    ]
