# Generated by Django 5.2.6 on 2025-12-18 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0025_alter_answer_table_alter_category_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='answer',
            table='pybo_answer',
        ),
        migrations.AlterModelTable(
            name='category',
            table='pybo_category',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='pybo_comment',
        ),
        migrations.AlterModelTable(
            name='game2048',
            table='pybo_game2048',
        ),
        migrations.AlterModelTable(
            name='guestbook',
            table='pybo_guestbook',
        ),
        migrations.AlterModelTable(
            name='minesweepergame',
            table='pybo_minesweepergame',
        ),
        migrations.AlterModelTable(
            name='numberbaseballattempt',
            table='pybo_numberbaseballattempt',
        ),
        migrations.AlterModelTable(
            name='numberbaseballgame',
            table='pybo_numberbaseballgame',
        ),
        migrations.AlterModelTable(
            name='question',
            table='pybo_question',
        ),
        migrations.AlterModelTable(
            name='tictactoegame',
            table='pybo_tictactoegame',
        ),
        migrations.AlterModelTable(
            name='wordchainchatmessage',
            table='pybo_wordchainchatmessage',
        ),
        migrations.AlterModelTable(
            name='wordchainentry',
            table='pybo_wordchainentry',
        ),
        migrations.AlterModelTable(
            name='wordchaingame',
            table='pybo_wordchaingame',
        ),
    ]
