# Generated by Django 5.2.6 on 2025-12-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0026_alter_answer_table_alter_category_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('dev', '개발 프로젝트'), ('work', '업무 경력'), ('education', '교육'), ('certificate', '자격증'), ('award', '수상'), ('activity', '활동'), ('other', '기타')], default='dev', max_length=20, verbose_name='타입'),
        ),
    ]
