# Generated by Django 5.2.6 on 2025-12-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0027_project_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='hero_gradient',
            field=models.CharField(default='linear-gradient(135deg, #667eea 0%, #764ba2 100%)', max_length=200, verbose_name='히어로 배경'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='skills_gradient',
            field=models.CharField(default='linear-gradient(135deg, #f093fb 0%, #f5576c 100%)', max_length=200, verbose_name='스킬 배경'),
        ),
        migrations.AddField(
            model_name='project',
            name='background_gradient',
            field=models.CharField(default='linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)', max_length=200, verbose_name='배경 그라데이션'),
        ),
    ]
