# Generated by Django 5.2.6 on 2025-12-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0028_portfolio_hero_gradient_portfolio_skills_gradient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='display_name',
            field=models.CharField(blank=True, default='', help_text='포트폴리오에 표시될 이름 (비워두면 사용자명 사용)', max_length=100, verbose_name='표시 이름'),
        ),
    ]
