# Generated by Django 5.2.6 on 2025-12-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0029_portfolio_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='categorized_skills',
            field=models.JSONField(blank=True, default=dict, help_text='{"Office Skills": ["MS Word", "Excel"], "Languages": ["English", "Korean"], ...}', verbose_name='카테고리별 스킬'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='enabled_skill_types',
            field=models.JSONField(blank=True, default=list, help_text='["simple", "leveled", "categorized", "freetext"] 중 선택', verbose_name='활성화된 스킬 타입'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='free_text_skills',
            field=models.TextField(blank=True, default='', help_text='역량에 대한 자유로운 서술', verbose_name='자유형 스킬 설명'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='hero_background_type',
            field=models.CharField(choices=[('gradient', '그라데이션'), ('solid', '단색 (브랜드)'), ('white', '화이트'), ('custom', '커스텀 색상')], default='gradient', max_length=20, verbose_name='히어로 배경 타입'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='hero_custom_color',
            field=models.CharField(blank=True, default='', help_text='HEX 색상 코드 (예: #667eea)', max_length=7, verbose_name='히어로 커스텀 색상'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='hero_solid_color',
            field=models.CharField(blank=True, default='', help_text='브랜드 색상 gradient 값', max_length=200, verbose_name='히어로 단색 배경'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='skill_tags',
            field=models.JSONField(blank=True, default=list, help_text='자유형 설명과 함께 사용할 키워드 태그', verbose_name='스킬 태그'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='skills_background_type',
            field=models.CharField(choices=[('gradient', '그라데이션'), ('solid', '단색 (브랜드)'), ('white', '화이트'), ('custom', '커스텀 색상')], default='gradient', max_length=20, verbose_name='스킬 배경 타입'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='skills_custom_color',
            field=models.CharField(blank=True, default='', help_text='HEX 색상 코드 (예: #f093fb)', max_length=7, verbose_name='스킬 커스텀 색상'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='skills_solid_color',
            field=models.CharField(blank=True, default='', help_text='브랜드 색상 gradient 값', max_length=200, verbose_name='스킬 단색 배경'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='skills_with_levels',
            field=models.JSONField(blank=True, default=list, help_text='[{"name": "Excel", "level": "Expert"}, ...]', verbose_name='레벨별 스킬'),
        ),
    ]
