# Generated by Django 5.2.6 on 2025-12-24 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0030_enhanced_portfolio_backgrounds_and_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='show_experience',
            field=models.BooleanField(default=False, help_text='포트폴리오에 경력 사항 섹션 표시 여부', verbose_name='경력 사항 표시'),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200, verbose_name='회사/기관명')),
                ('position', models.CharField(max_length=100, verbose_name='직책/역할')),
                ('location', models.CharField(blank=True, default='', max_length=100, verbose_name='근무지')),
                ('start_date', models.DateField(verbose_name='시작일')),
                ('end_date', models.DateField(blank=True, help_text='재직 중인 경우 비워두세요', null=True, verbose_name='종료일')),
                ('is_current', models.BooleanField(default=False, verbose_name='현재 재직 중')),
                ('description', models.TextField(blank=True, default='', help_text='담당했던 주요 업무를 설명하세요', verbose_name='주요 업무')),
                ('achievements', models.JSONField(blank=True, default=list, help_text='["성과 1", "성과 2", ...] 형식으로 저장', verbose_name='주요 성과')),
                ('tech_stack', models.JSONField(blank=True, default=list, verbose_name='사용 기술')),
                ('order', models.IntegerField(default=0, help_text='작은 숫자가 위에 표시됩니다', verbose_name='순서')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='community.portfolio', verbose_name='포트폴리오')),
            ],
            options={
                'verbose_name': '경력 사항',
                'verbose_name_plural': '경력 사항 목록',
                'db_table': 'pybo_experience',
                'ordering': ['order', '-start_date'],
            },
        ),
    ]
