# Generated by Django 5.2.6 on 2025-12-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0031_portfolio_show_experience_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='날짜')),
                ('visitor_count', models.PositiveIntegerField(default=0, verbose_name='방문자 수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '일일 방문자',
                'verbose_name_plural': '일일 방문자 통계',
                'db_table': 'pybo_daily_visitor',
                'ordering': ['-date'],
            },
        ),
    ]
