# Generated by Django 5.2.6 on 2025-12-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0032_dailyvisitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='create_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='create_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='view_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
