# Generated by Django 5.2.6 on 2026-02-09 13:39

import community.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0033_alter_answer_create_date_alter_answer_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='question_files/', validators=[community.validators.validate_question_file]),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', validators=[community.validators.validate_image_file]),
        ),
    ]
