# Generated by Django 5.2.6 on 2026-02-25 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0034_alter_question_file_alter_question_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_name', models.CharField(max_length=100, verbose_name='포트폴리오 이름')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='URL 슬러그')),
                ('is_published', models.BooleanField(default=False, verbose_name='게시 여부')),
                ('is_main', models.BooleanField(default=False, verbose_name='대표 포트폴리오')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='정렬 순서')),
                ('display_name', models.CharField(blank=True, default='', max_length=100, verbose_name='표시 이름')),
                ('title', models.CharField(blank=True, default='', max_length=100, verbose_name='직업/역할')),
                ('bio', models.TextField(blank=True, default='', max_length=500, verbose_name='자기소개')),
                ('location', models.CharField(blank=True, default='', max_length=100, verbose_name='위치')),
                ('email', models.EmailField(blank=True, default='', max_length=100, verbose_name='이메일')),
                ('github_url', models.URLField(blank=True, default='', verbose_name='GitHub URL')),
                ('linkedin_url', models.URLField(blank=True, default='', verbose_name='LinkedIn URL')),
                ('website_url', models.URLField(blank=True, default='', verbose_name='개인 웹사이트')),
                ('skills', models.JSONField(blank=True, default=list, verbose_name='기술 스택')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='portfolio/profiles/', verbose_name='프로필 이미지')),
                ('hero_gradient', models.CharField(default='linear-gradient(135deg, #667eea 0%, #764ba2 100%)', max_length=200, verbose_name='히어로 배경')),
                ('skills_gradient', models.CharField(default='linear-gradient(135deg, #f093fb 0%, #f5576c 100%)', max_length=200, verbose_name='스킬 배경')),
                ('hero_background_type', models.CharField(choices=[('gradient', '그라데이션'), ('solid', '단색 (브랜드)'), ('white', '화이트'), ('custom', '커스텀 색상')], default='gradient', max_length=20, verbose_name='히어로 배경 타입')),
                ('skills_background_type', models.CharField(choices=[('gradient', '그라데이션'), ('solid', '단색 (브랜드)'), ('white', '화이트'), ('custom', '커스텀 색상')], default='gradient', max_length=20, verbose_name='스킬 배경 타입')),
                ('hero_custom_color', models.CharField(blank=True, default='', max_length=7, verbose_name='히어로 커스텀 색상')),
                ('skills_custom_color', models.CharField(blank=True, default='', max_length=7, verbose_name='스킬 커스텀 색상')),
                ('hero_solid_color', models.CharField(blank=True, default='', max_length=200, verbose_name='히어로 단색 배경')),
                ('skills_solid_color', models.CharField(blank=True, default='', max_length=200, verbose_name='스킬 단색 배경')),
                ('skills_with_levels', models.JSONField(blank=True, default=list, verbose_name='레벨별 스킬')),
                ('categorized_skills', models.JSONField(blank=True, default=dict, verbose_name='카테고리별 스킬')),
                ('free_text_skills', models.TextField(blank=True, default='', verbose_name='자유형 스킬 설명')),
                ('skill_tags', models.JSONField(blank=True, default=list, verbose_name='스킬 태그')),
                ('enabled_skill_types', models.JSONField(blank=True, default=list, verbose_name='활성화된 스킬 타입')),
                ('theme', models.CharField(choices=[('light', '라이트 모드'), ('dark', '다크 모드')], default='light', max_length=10, verbose_name='테마')),
                ('show_experience', models.BooleanField(default=False, verbose_name='경력 사항 표시')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_collections', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '포트폴리오 컬렉션',
                'verbose_name_plural': '포트폴리오 컬렉션 목록',
                'db_table': 'community_portfolio_collection',
                'ordering': ['display_order', '-create_date'],
            },
        ),
        migrations.CreateModel(
            name='CollectionProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='프로젝트 제목')),
                ('description', models.TextField(verbose_name='프로젝트 설명')),
                ('project_type', models.CharField(choices=[('dev', '개발 프로젝트'), ('work', '업무 경력'), ('education', '교육'), ('certificate', '자격증'), ('award', '수상'), ('activity', '활동'), ('other', '기타')], default='dev', max_length=20, verbose_name='타입')),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/projects/', verbose_name='프로젝트 이미지')),
                ('tech_stack', models.JSONField(blank=True, default=list, verbose_name='기술 스택')),
                ('project_url', models.URLField(blank=True, default='', verbose_name='프로젝트 URL')),
                ('github_url', models.URLField(blank=True, default='', verbose_name='GitHub URL')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='시작일')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='종료일')),
                ('background_gradient', models.CharField(default='linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)', max_length=200, verbose_name='배경 그라데이션')),
                ('order', models.IntegerField(default=0, verbose_name='순서')),
                ('is_featured', models.BooleanField(default=False, verbose_name='추천 프로젝트')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('portfolio_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='community.portfoliocollection', verbose_name='포트폴리오')),
            ],
            options={
                'verbose_name': '컬렉션 프로젝트',
                'verbose_name_plural': '컬렉션 프로젝트 목록',
                'db_table': 'community_collection_project',
                'ordering': ['order', '-create_date'],
            },
        ),
        migrations.CreateModel(
            name='CollectionExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200, verbose_name='회사/기관명')),
                ('position', models.CharField(max_length=100, verbose_name='직책/역할')),
                ('location', models.CharField(blank=True, default='', max_length=100, verbose_name='근무지')),
                ('start_date', models.DateField(verbose_name='시작일')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='종료일')),
                ('is_current', models.BooleanField(default=False, verbose_name='현재 재직 중')),
                ('description', models.TextField(blank=True, default='', verbose_name='주요 업무')),
                ('achievements', models.JSONField(blank=True, default=list, verbose_name='주요 성과')),
                ('tech_stack', models.JSONField(blank=True, default=list, verbose_name='사용 기술')),
                ('order', models.IntegerField(default=0, verbose_name='순서')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('portfolio_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='community.portfoliocollection', verbose_name='포트폴리오')),
            ],
            options={
                'verbose_name': '컬렉션 경력 사항',
                'verbose_name_plural': '컬렉션 경력 사항 목록',
                'db_table': 'community_collection_experience',
                'ordering': ['order', '-start_date'],
            },
        ),
        migrations.AddIndex(
            model_name='portfoliocollection',
            index=models.Index(fields=['slug'], name='community_p_slug_a290bd_idx'),
        ),
        migrations.AddIndex(
            model_name='portfoliocollection',
            index=models.Index(fields=['user', 'is_published'], name='community_p_user_id_ab6256_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='portfoliocollection',
            unique_together={('user', 'portfolio_name')},
        ),
    ]
