# Generated by Django 5.2.6 on 2026-02-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0035_create_portfolio_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='hero_background_image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/hero_backgrounds/', verbose_name='히어로 배경 이미지'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='hero_image_overlay_opacity',
            field=models.PositiveSmallIntegerField(default=40, verbose_name='오버레이 투명도 (%)'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='hero_image_position_x',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='배경 X 위치 (%)'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='hero_image_position_y',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='배경 Y 위치 (%)'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='hero_image_zoom',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='배경 확대 비율 (%)'),
        ),
        migrations.AddField(
            model_name='portfoliocollection',
            name='hero_background_image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/hero_backgrounds/', verbose_name='히어로 배경 이미지'),
        ),
        migrations.AddField(
            model_name='portfoliocollection',
            name='hero_image_overlay_opacity',
            field=models.PositiveSmallIntegerField(default=40, verbose_name='오버레이 투명도 (%)'),
        ),
        migrations.AddField(
            model_name='portfoliocollection',
            name='hero_image_position_x',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='배경 X 위치 (%)'),
        ),
        migrations.AddField(
            model_name='portfoliocollection',
            name='hero_image_position_y',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='배경 Y 위치 (%)'),
        ),
        migrations.AddField(
            model_name='portfoliocollection',
            name='hero_image_zoom',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='배경 확대 비율 (%)'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='hero_background_type',
            field=models.CharField(choices=[('gradient', '그라데이션'), ('solid', '단색 (브랜드)'), ('white', '화이트'), ('custom', '커스텀 색상'), ('image', '배경 이미지')], default='gradient', max_length=20, verbose_name='히어로 배경 타입'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='skills_background_type',
            field=models.CharField(choices=[('gradient', '그라데이션'), ('solid', '단색 (브랜드)'), ('white', '화이트'), ('custom', '커스텀 색상'), ('image', '배경 이미지')], default='gradient', max_length=20, verbose_name='스킬 배경 타입'),
        ),
        migrations.AlterField(
            model_name='portfoliocollection',
            name='hero_background_type',
            field=models.CharField(choices=[('gradient', '그라데이션'), ('solid', '단색 (브랜드)'), ('white', '화이트'), ('custom', '커스텀 색상'), ('image', '배경 이미지')], default='gradient', max_length=20, verbose_name='히어로 배경 타입'),
        ),
        migrations.AlterField(
            model_name='portfoliocollection',
            name='skills_background_type',
            field=models.CharField(choices=[('gradient', '그라데이션'), ('solid', '단색 (브랜드)'), ('white', '화이트'), ('custom', '커스텀 색상'), ('image', '배경 이미지')], default='gradient', max_length=20, verbose_name='스킬 배경 타입'),
        ),
    ]
