# Generated by Django 5.2.6 on 2026-06-04 14:36

import community.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0036_add_hero_background_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='questions/', validators=[community.validators.validate_image_file])),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='community.question')),
            ],
            options={
                'db_table': 'pybo_question_image',
                'ordering': ['id'],
            },
        ),
    ]
