# Generated by Django 5.2.6 on 2026-06-07 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0037_questionimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='approval_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='게시 요청일'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='approval_status',
            field=models.CharField(choices=[('draft', '작성 중'), ('pending', '승인 대기'), ('approved', '승인됨'), ('rejected', '반려됨')], default='draft', max_length=10, verbose_name='승인 상태'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', verbose_name='반려 사유'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='검토일'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='검토 관리자'),
        ),
        migrations.AddField(
            model_name='portfoliocollection',
            name='approval_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='게시 요청일'),
        ),
        migrations.AddField(
            model_name='portfoliocollection',
            name='approval_status',
            field=models.CharField(choices=[('draft', '작성 중'), ('pending', '승인 대기'), ('approved', '승인됨'), ('rejected', '반려됨')], default='draft', max_length=10, verbose_name='승인 상태'),
        ),
        migrations.AddField(
            model_name='portfoliocollection',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', verbose_name='반려 사유'),
        ),
        migrations.AddField(
            model_name='portfoliocollection',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='검토일'),
        ),
        migrations.AddField(
            model_name='portfoliocollection',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='검토 관리자'),
        ),
    ]
