# Generated by Django 5.2.6 on 2026-07-16 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0039_grandfather_existing_portfolios'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='episode_number',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='시리즈 내 회차 (0=오리엔테이션)', null=True),
        ),
        migrations.CreateModel(
            name='ColumnSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('audience', models.CharField(blank=True, help_text='대상 독자 (프롬프트에 사용)', max_length=200)),
                ('total_episodes', models.PositiveIntegerField(default=0, help_text='기획된 총 회차 수 (0편 포함)')),
                ('is_active', models.BooleanField(default=True, help_text='자동 발행 대상 여부')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series', to='community.category')),
            ],
            options={
                'verbose_name': '칼럼 시리즈',
                'verbose_name_plural': '칼럼 시리즈',
                'ordering': ['-create_date'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='episodes', to='community.columnseries'),
        ),
    ]
