# Generated by Django 5.2.6 on 2026-08-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0040_question_episode_number_columnseries_question_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliocollection',
            name='content_mode',
            field=models.CharField(choices=[('builder', '빌더 (구성형)'), ('html', 'HTML 직접 업로드')], default='builder', max_length=10, verbose_name='표현 방식'),
        ),
        migrations.AddField(
            model_name='portfoliocollection',
            name='html_content',
            field=models.TextField(blank=True, default='', verbose_name='업로드 HTML 원본'),
        ),
        migrations.AddField(
            model_name='portfoliocollection',
            name='html_filename',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='업로드 파일명'),
        ),
    ]
