# Generated by Django 5.2.6 on 2026-08-04 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0041_portfoliocollection_content_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/html_assets/', verbose_name='이미지')),
                ('original_name', models.CharField(max_length=255, verbose_name='원본 파일명')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='업로드일')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='html_assets', to='community.portfoliocollection', verbose_name='포트폴리오')),
            ],
            options={
                'verbose_name': 'HTML 포트폴리오 이미지',
                'verbose_name_plural': 'HTML 포트폴리오 이미지 목록',
                'db_table': 'community_portfolio_asset',
                'ordering': ['create_date'],
            },
        ),
    ]
