# Generated by Django 5.2.6 on 2026-09-17 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0042_portfolioasset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(db_index=True, verbose_name='회의 주차(월요일)')),
                ('held_at', models.DateTimeField(auto_now_add=True, verbose_name='개최일시')),
                ('status', models.CharField(choices=[('open', '결정 대기'), ('closed', '결정 완료')], default='open', max_length=10)),
                ('briefing', models.TextField(blank=True, verbose_name='팀장 지표 브리핑')),
                ('transcript', models.JSONField(default=list, verbose_name='회의록')),
                ('snapshot', models.JSONField(default=dict, verbose_name='수집 데이터 스냅샷')),
                ('summary', models.TextField(blank=True, verbose_name='결론 요약')),
            ],
            options={
                'verbose_name': '편집회의',
                'verbose_name_plural': '편집회의',
                'ordering': ['-held_at'],
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('column', '칼럼 주제'), ('series', '시리즈 방향'), ('dev', '개발·개선'), ('ops', '운영·보안')], db_index=True, max_length=10)),
                ('topic', models.CharField(blank=True, db_index=True, max_length=10, verbose_name='칼럼 분야 키')),
                ('question', models.CharField(max_length=300, verbose_name='안건')),
                ('options', models.JSONField(default=list)),
                ('chosen_key', models.CharField(blank=True, db_index=True, max_length=20)),
                ('chosen_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='관리자 메모')),
                ('consumed_at', models.DateTimeField(blank=True, null=True, verbose_name='칼럼에 반영된 시각')),
                ('chosen_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='office.meeting')),
            ],
            options={
                'ordering': ['meeting', 'kind', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ColumnDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(db_index=True, max_length=10)),
                ('brief', models.CharField(blank=True, max_length=300, verbose_name='회의에서 정한 주제')),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(blank=True, verbose_name='최종 본문(마크다운)')),
                ('chart_path', models.CharField(blank=True, max_length=300, verbose_name='차트 이미지 (media 상대경로)')),
                ('check_report', models.JSONField(default=dict, verbose_name='검증관 보고')),
                ('qa_report', models.JSONField(default=dict, verbose_name='팀장 QA')),
                ('revisions', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('published', '발행'), ('hold', '검수 대기'), ('rejected', '반려'), ('failed', '실패')], db_index=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('question', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office_draft', to='community.question')),
                ('decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='office.decision')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(db_index=True, max_length=10)),
                ('action', models.CharField(db_index=True, max_length=40)),
                ('text', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='office.columndraft')),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='office.meeting')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
