# Generated by Django 5.2.6 on 2026-09-24 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='columndraft',
            name='admin_note',
            field=models.TextField(blank=True, verbose_name='운영자 수정 지시'),
        ),
        migrations.AddField(
            model_name='columndraft',
            name='chart_note',
            field=models.CharField(blank=True, max_length=300, verbose_name='시각화 결과·사유'),
        ),
        migrations.AlterField(
            model_name='columndraft',
            name='check_report',
            field=models.JSONField(default=dict, verbose_name='팩트체크 보고'),
        ),
        migrations.AlterField(
            model_name='columndraft',
            name='qa_report',
            field=models.JSONField(default=dict, verbose_name='편집 심사 결과'),
        ),
        migrations.AlterField(
            model_name='columndraft',
            name='status',
            field=models.CharField(choices=[('published', '발행'), ('hold', '검수 대기'), ('revising', '재작성 중'), ('rejected', '반려'), ('failed', '실패')], db_index=True, max_length=10),
        ),
    ]
