# Generated by Django 5.2.6 on 2026-09-24 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_logfinding'),
        ('office', '0002_columndraft_admin_note_columndraft_chart_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('meeting', '편집회의 결정'), ('finding', '로그 지적사항'), ('manual', '직접 등록')], db_index=True, default='manual', max_length=10)),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField(blank=True, verbose_name='배경·완료 조건')),
                ('kind', models.CharField(choices=[('dev', '개발·개선'), ('ops', '운영·보안'), ('bug', '버그'), ('chore', '정리')], db_index=True, default='dev', max_length=10)),
                ('priority', models.CharField(db_index=True, default='P2', max_length=2)),
                ('status', models.CharField(choices=[('backlog', '접수'), ('approved', '승인'), ('working', '작업 중'), ('pr_open', 'PR 열림'), ('done', '완료'), ('rejected', '반려'), ('failed', '실패')], db_index=True, default='backlog', max_length=10)),
                ('triage', models.JSONField(default=dict, verbose_name='분류 결과(담당·난이도·완료조건)')),
                ('hints', models.JSONField(default=list, verbose_name='관련 파일 후보')),
                ('plan', models.JSONField(default=dict, verbose_name='원인·수정 계획')),
                ('result', models.JSONField(default=dict, verbose_name='패치·검증 결과')),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('issue_number', models.PositiveIntegerField(blank=True, null=True)),
                ('issue_url', models.URLField(blank=True)),
                ('branch', models.CharField(blank=True, max_length=120)),
                ('pr_url', models.URLField(blank=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='office.decision')),
                ('finding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='common.logfinding')),
            ],
            options={
                'verbose_name': '정비 작업',
                'verbose_name_plural': '정비 작업',
                'ordering': ['priority', '-created_at'],
            },
        ),
    ]
