# Generated by Django 5.2.6 on 2026-09-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='public_text',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='공개용 문장'),
        ),
    ]
