# Generated by Django 5.2.6 on 2026-09-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0004_worklog_public_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='public_note',
            field=models.CharField(blank=True, max_length=300, verbose_name='공개용 소개'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='public_summary',
            field=models.TextField(blank=True, verbose_name='공개용 요약'),
        ),
    ]
