# Generated by Django 5.2.6 on 2026-10-07 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0042_portfolioasset'),
        ('office', '0005_decision_public_note_meeting_public_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.UUIDField(db_index=True)),
                ('seq', models.PositiveSmallIntegerField()),
                ('stage', models.CharField(db_index=True, max_length=40)),
                ('agent', models.CharField(blank=True, max_length=10)),
                ('sender', models.CharField(blank=True, max_length=10)),
                ('recipient', models.CharField(blank=True, max_length=10)),
                ('kind', models.CharField(blank=True, max_length=20)),
                ('attempt', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(default='ok', max_length=10)),
                ('output', models.JSONField(default=dict)),
                ('text_digest', models.CharField(blank=True, max_length=64)),
                ('seconds', models.FloatField(default=0)),
                ('calls', models.JSONField(default=list)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='office.columndraft')),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='office.meeting')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='community.question')),
            ],
            options={
                'verbose_name': '제작 단계 기록',
                'verbose_name_plural': '제작 단계 기록',
                'ordering': ['run_id', 'seq'],
            },
        ),
    ]
