# Generated by Django 5.2.6 on 2026-10-09 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0006_stagerun'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifiedFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim', models.CharField(max_length=500, verbose_name='주장')),
                ('claim_key', models.CharField(db_index=True, max_length=200, verbose_name='중복 판별 키')),
                ('status', models.CharField(db_index=True, max_length=15)),
                ('note', models.TextField(blank=True)),
                ('urls', models.JSONField(default=list)),
                ('method', models.CharField(blank=True, max_length=20, verbose_name='확인 방법')),
                ('times_seen', models.PositiveIntegerField(default=1)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '검증 원장',
                'verbose_name_plural': '검증 원장',
                'ordering': ['-last_seen'],
            },
        ),
    ]
