# Generated by Django 5.2.6 on 2026-10-09 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0042_portfolioasset'),
        ('office', '0007_verifiedfact'),
    ]

    operations = [
        migrations.AddField(
            model_name='columndraft',
            name='episode_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='연재 회차'),
        ),
        migrations.AddField(
            model_name='columndraft',
            name='series_key',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='연재 시리즈 키'),
        ),
        migrations.AddField(
            model_name='columndraft',
            name='target_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='community.question', verbose_name='리메이크 대상 글'),
        ),
    ]
