# Generated by Django 5.2.6 on 2026-10-10 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0042_portfolioasset'),
        ('office', '0008_columndraft_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnDigest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtopic', models.CharField(max_length=60, verbose_name='소주제')),
                ('keywords', models.JSONField(default=list, verbose_name='키워드')),
                ('summary', models.TextField(verbose_name='요약')),
                ('content_hash', models.CharField(max_length=40, verbose_name='요약한 본문의 해시')),
                ('source', models.CharField(default='lab', max_length=20, verbose_name='작성 경로')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digest', to='community.question')),
            ],
            options={
                'verbose_name': '칼럼 지도 항목',
                'verbose_name_plural': '칼럼 지도 항목',
            },
        ),
    ]
