# Generated by Django 5.2.6 on 2025-10-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0014_wordchaingame_wordchainchatmessage_wordchainentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='question_files/'),
        ),
    ]
