# Generated by Django 5.2.6 on 2025-10-23 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0015_question_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wordchaingame',
            name='current_turn',
            field=models.ForeignKey(blank=True, help_text='현재 차례인 사용자', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_turn_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wordchaingame',
            name='max_participants',
            field=models.IntegerField(default=4, help_text='최대 참가자 수'),
        ),
        migrations.AddField(
            model_name='wordchaingame',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='wordchain_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wordchaingame',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='게임 시작 시간', null=True),
        ),
        migrations.AlterField(
            model_name='wordchaingame',
            name='status',
            field=models.CharField(choices=[('waiting', '대기중'), ('active', '진행중'), ('finished', '종료됨')], default='waiting', max_length=20),
        ),
    ]
