# Generated by Django 5.2.6 on 2025-10-27 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0018_guestbook_numberbaseballgame_numberbaseballattempt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game2048',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_state', models.JSONField(default=list, verbose_name='보드 상태')),
                ('score', models.IntegerField(default=0, verbose_name='점수')),
                ('best_score', models.IntegerField(default=0, verbose_name='최고 점수')),
                ('status', models.CharField(choices=[('playing', '진행중'), ('won', '승리'), ('lost', '패배')], default='playing', max_length=10, verbose_name='상태')),
                ('moves', models.IntegerField(default=0, verbose_name='이동 횟수')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='종료일')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game2048_records', to=settings.AUTH_USER_MODEL, verbose_name='플레이어')),
            ],
            options={
                'verbose_name': '2048 게임',
                'verbose_name_plural': '2048 게임 기록',
                'ordering': ['-create_date'],
            },
        ),
    ]
