# Generated by Django 5.2.6 on 2025-10-28 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0020_alter_game2048_best_score_alter_game2048_create_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MinesweeperGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('easy', '쉬움 (9x9, 10개)'), ('medium', '보통 (16x16, 40개)'), ('hard', '어려움 (16x30, 99개)')], default='easy', max_length=10, verbose_name='난이도')),
                ('rows', models.IntegerField(default=9, verbose_name='행 수')),
                ('cols', models.IntegerField(default=9, verbose_name='열 수')),
                ('mines_count', models.IntegerField(default=10, verbose_name='지뢰 수')),
                ('board_state', models.JSONField(default=dict, verbose_name='보드 상태')),
                ('status', models.CharField(choices=[('playing', '진행중'), ('won', '승리'), ('lost', '패배')], db_index=True, default='playing', max_length=10, verbose_name='상태')),
                ('time_elapsed', models.IntegerField(default=0, verbose_name='소요 시간 (초)')),
                ('create_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='생성일')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='종료일')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minesweeper_games', to=settings.AUTH_USER_MODEL, verbose_name='플레이어')),
            ],
            options={
                'verbose_name': '지뢰찾기 게임',
                'verbose_name_plural': '지뢰찾기 게임 기록',
                'ordering': ['-create_date'],
                'indexes': [models.Index(fields=['player', 'status'], name='ms_player_status_idx'), models.Index(fields=['player', 'difficulty', '-time_elapsed'], name='ms_player_diff_time_idx')],
            },
        ),
    ]
