# Generated by Django 5.2.6 on 2025-10-28 05:09

import pybo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0021_minesweepergame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minesweepergame',
            name='board_state',
            field=models.JSONField(default=pybo.models.get_default_board_state, verbose_name='보드 상태'),
        ),
    ]
